### ISSUE TITLE
App master folder should be resolved manually

### ISSUE THREAD

**Issue by SkyCrawl** [passiomatic/coldsweat#102]
When I run coldsweat like this:
```python
python ./coldsweat/sweat.py serve -r -p 3333 > /dev/null &
```

I get the following traceback:
```
Traceback (most recent call last):
  File "./coldsweat/sweat.py", line 12, in <module>
    run()
  File "<full-path>/coldsweat/coldsweat/commands.py", line 261, in run
    cc.run_command(command_name, command_options, command_args)
  File "<full-path>coldsweat/coldsweat/commands.py", line 65, in run_command
    handler(options, args)        
  File "<full-path>/coldsweat/coldsweat/commands.py", line 138, in command_serve
    static_app = DirectoryApp("static", index_page=None)
  File "/opt/lib/python2.7/site-packages/webob/static.py", line 127, in __init__
    "Path does not exist or is not directory: %r" % self.path)
IOError: Path does not exist or is not directory: '<full-path>/static/'
```

The hardcoded relative URL `static` in `static_app = DirectoryApp("static", index_page=None)` seems not to play well with the current working directory. A tiny issue that can be resolved user-side but eventually, you might be in the mood to eliminate it :).

**Comment by passiomatic** [comment]
Should be fixed now.
