### ISSUE TITLE
Fetch doesn't seem to work. Produces errors

### ISSUE THREAD

**Issue by richardsonsamuel** [passiomatic/coldsweat#112]
It returns this error. 

`
$ python sweat.py fetch
Process PoolWorker-1:
Traceback (most recent call last):
Process PoolWorker-2:
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
Process PoolWorker-3:
Traceback (most recent call last):
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
    self.run()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/process.py", line 114, in run
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/process.py", line 114, in run
    self.run()
    self._target(*self._args, **self._kwargs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/process.py", line 114, in run
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/pool.py", line 97, in worker
    self._target(*self._args, **self._kwargs)
    self._target(*self._args, **self._kwargs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/pool.py", line 97, in worker
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/pool.py", line 97, in worker
    initializer(*initargs)
  File "/Users/samuelrichardson/Library/Mobile Documents/com~apple~CloudDocs/dev-new/coldsweat/coldsweat/models.py", line 326, in connect
    initializer(*initargs)
  File "/Users/samuelrichardson/Library/Mobile Documents/com~apple~CloudDocs/dev-new/coldsweat/coldsweat/models.py", line 326, in connect
    _db.connect()
  File "/Library/Python/2.7/site-packages/peewee.py", line 3296, in connect
    _db.connect()
    initializer(*initargs)
  File "/Library/Python/2.7/site-packages/peewee.py", line 3296, in connect
  File "/Users/samuelrichardson/Library/Mobile Documents/com~apple~CloudDocs/dev-new/coldsweat/coldsweat/models.py", line 326, in connect
    _db.connect()
  File "/Library/Python/2.7/site-packages/peewee.py", line 3296, in connect
    self.initialize_connection(self.__local.conn)
  File "/Library/Python/2.7/site-packages/peewee.py", line 3212, in __exit__
    self.initialize_connection(self.__local.conn)
    reraise(new_type, new_type(*exc_args), traceback)
  File "/Library/Python/2.7/site-packages/peewee.py", line 3212, in __exit__
  File "/Library/Python/2.7/site-packages/peewee.py", line 3294, in connect
    **self.connect_kwargs)
    reraise(new_type, new_type(*exc_args), traceback)
  File "/Library/Python/2.7/site-packages/peewee.py", line 3514, in _connect
  File "/Library/Python/2.7/site-packages/peewee.py", line 3294, in connect
    self._add_conn_hooks(conn)
    **self.connect_kwargs)
  File "/Library/Python/2.7/site-packages/peewee.py", line 3521, in _add_conn_hooks
  File "/Library/Python/2.7/site-packages/peewee.py", line 3514, in _connect
    self._set_pragmas(conn)
  File "/Library/Python/2.7/site-packages/peewee.py", line 3530, in _set_pragmas
    self._add_conn_hooks(conn)
  File "/Library/Python/2.7/site-packages/peewee.py", line 3521, in _add_conn_hooks
    cursor.execute('PRAGMA %s = %s;' % (pragma, value))
    self._set_pragmas(conn)
  File "/Library/Python/2.7/site-packages/peewee.py", line 3530, in _set_pragmas
    cursor.execute('PRAGMA %s = %s;' % (pragma, value))
OperationalError: locking protocol
OperationalError: locking protocol
Process PoolWorker-4:
Traceback (most recent call last):
    self.initialize_connection(self.__local.conn)
  File "/Library/Python/2.7/site-packages/peewee.py", line 3212, in __exit__
    reraise(new_type, new_type(*exc_args), traceback)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
  File "/Library/Python/2.7/site-packages/peewee.py", line 3294, in connect
    **self.connect_kwargs)
  File "/Library/Python/2.7/site-packages/peewee.py", line 3514, in _connect
    self._add_conn_hooks(conn)
  File "/Library/Python/2.7/site-packages/peewee.py", line 3521, in _add_conn_hooks
    self._set_pragmas(conn)
  File "/Library/Python/2.7/site-packages/peewee.py", line 3530, in _set_pragmas
    cursor.execute('PRAGMA %s = %s;' % (pragma, value))
OperationalError: locking protocol
    self.run()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/pool.py", line 97, in worker
    initializer(*initargs)
  File "/Users/samuelrichardson/Library/Mobile Documents/com~apple~CloudDocs/dev-new/coldsweat/coldsweat/models.py", line 326, in connect
    _db.connect()
  File "/Library/Python/2.7/site-packages/peewee.py", line 3296, in connect
    self.initialize_connection(self.__local.conn)
  File "/Library/Python/2.7/site-packages/peewee.py", line 3212, in __exit__
    reraise(new_type, new_type(*exc_args), traceback)
  File "/Library/Python/2.7/site-packages/peewee.py", line 3294, in connect
    **self.connect_kwargs)
  File "/Library/Python/2.7/site-packages/peewee.py", line 3514, in _connect
    self._add_conn_hooks(conn)
  File "/Library/Python/2.7/site-packages/peewee.py", line 3521, in _add_conn_hooks
    self._set_pragmas(conn)
  File "/Library/Python/2.7/site-packages/peewee.py", line 3530, in _set_pragmas
    cursor.execute('PRAGMA %s = %s;' % (pragma, value))
OperationalError: locking protocol
Process PoolWorker-5:
Process PoolWorker-6:
Traceback (most recent call last):
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
    self.run()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/pool.py", line 97, in worker
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/pool.py", line 97, in worker
    initializer(*initargs)
  File "/Users/samuelrichardson/Library/Mobile Documents/com~apple~CloudDocs/dev-new/coldsweat/coldsweat/models.py", line 326, in connect
    initializer(*initargs)
  File "/Users/samuelrichardson/Library/Mobile Documents/com~apple~CloudDocs/dev-new/coldsweat/coldsweat/models.py", line 326, in connect
    _db.connect()
  File "/Library/Python/2.7/site-packages/peewee.py", line 3296, in connect
    _db.connect()
  File "/Library/Python/2.7/site-packages/peewee.py", line 3296, in connect
    self.initialize_connection(self.__local.conn)
  File "/Library/Python/2.7/site-packages/peewee.py", line 3212, in __exit__
    reraise(new_type, new_type(*exc_args), traceback)
  File "/Library/Python/2.7/site-packages/peewee.py", line 3294, in connect
    **self.connect_kwargs)
  File "/Library/Python/2.7/site-packages/peewee.py", line 3514, in _connect
    self._add_conn_hooks(conn)
  File "/Library/Python/2.7/site-packages/peewee.py", line 3521, in _add_conn_hooks
    self.initialize_connection(self.__local.conn)
    self._set_pragmas(conn)
  File "/Library/Python/2.7/site-packages/peewee.py", line 3212, in __exit__
  File "/Library/Python/2.7/site-packages/peewee.py", line 3530, in _set_pragmas
    cursor.execute('PRAGMA %s = %s;' % (pragma, value))
    reraise(new_type, new_type(*exc_args), traceback)
  File "/Library/Python/2.7/site-packages/peewee.py", line 3294, in connect
    **self.connect_kwargs)
  File "/Library/Python/2.7/site-packages/peewee.py", line 3514, in _connect
    self._add_conn_hooks(conn)
  File "/Library/Python/2.7/site-packages/peewee.py", line 3521, in _add_conn_hooks
OperationalError: locking protocol
    self._set_pragmas(conn)
  File "/Library/Python/2.7/site-packages/peewee.py", line 3530, in _set_pragmas
    cursor.execute('PRAGMA %s = %s;' % (pragma, value))
OperationalError: locking protocol
Process PoolWorker-8:
Process PoolWorker-7:
Traceback (most recent call last):
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/pool.py", line 97, in worker
    self.run()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/pool.py", line 97, in worker
    initializer(*initargs)
  File "/Users/samuelrichardson/Library/Mobile Documents/com~apple~CloudDocs/dev-new/coldsweat/coldsweat/models.py", line 326, in connect
    initializer(*initargs)
  File "/Users/samuelrichardson/Library/Mobile Documents/com~apple~CloudDocs/dev-new/coldsweat/coldsweat/models.py", line 326, in connect
    _db.connect()
  File "/Library/Python/2.7/site-packages/peewee.py", line 3296, in connect
    _db.connect()
  File "/Library/Python/2.7/site-packages/peewee.py", line 3296, in connect
    self.initialize_connection(self.__local.conn)
  File "/Library/Python/2.7/site-packages/peewee.py", line 3212, in __exit__
    reraise(new_type, new_type(*exc_args), traceback)
  File "/Library/Python/2.7/site-packages/peewee.py", line 3294, in connect
    **self.connect_kwargs)
  File "/Library/Python/2.7/site-packages/peewee.py", line 3514, in _connect
    self._add_conn_hooks(conn)
  File "/Library/Python/2.7/site-packages/peewee.py", line 3521, in _add_conn_hooks
    self._set_pragmas(conn)
  File "/Library/Python/2.7/site-packages/peewee.py", line 3530, in _set_pragmas
    cursor.execute('PRAGMA %s = %s;' % (pragma, value))
OperationalError: locking protocol
    self.initialize_connection(self.__local.conn)
  File "/Library/Python/2.7/site-packages/peewee.py", line 3212, in __exit__
    reraise(new_type, new_type(*exc_args), traceback)
  File "/Library/Python/2.7/site-packages/peewee.py", line 3294, in connect
    **self.connect_kwargs)
  File "/Library/Python/2.7/site-packages/peewee.py", line 3514, in _connect
    self._add_conn_hooks(conn)
  File "/Library/Python/2.7/site-packages/peewee.py", line 3521, in _add_conn_hooks
    self._set_pragmas(conn)
  File "/Library/Python/2.7/site-packages/peewee.py", line 3530, in _set_pragmas
    cursor.execute('PRAGMA %s = %s;' % (pragma, value))
OperationalError: locking protocol
Process PoolWorker-12:
Process PoolWorker-10:
Process PoolWorker-9:
Process PoolWorker-11:
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/process.py", line 114, in run
    self.run()
    self.run()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/process.py", line 114, in run
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/process.py", line 114, in run
    self.run()
    self._target(*self._args, **self._kwargs)
    self._target(*self._args, **self._kwargs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/process.py", line 114, in run
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/pool.py", line 97, in worker
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/pool.py", line 97, in worker
    self._target(*self._args, **self._kwargs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/pool.py", line 97, in worker
    self._target(*self._args, **self._kwargs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/pool.py", line 97, in worker
    initializer(*initargs)
  File "/Users/samuelrichardson/Library/Mobile Documents/com~apple~CloudDocs/dev-new/coldsweat/coldsweat/models.py", line 326, in connect
    initializer(*initargs)
  File "/Users/samuelrichardson/Library/Mobile Documents/com~apple~CloudDocs/dev-new/coldsweat/coldsweat/models.py", line 326, in connect
    _db.connect()
  File "/Library/Python/2.7/site-packages/peewee.py", line 3296, in connect
    initializer(*initargs)
  File "/Users/samuelrichardson/Library/Mobile Documents/com~apple~CloudDocs/dev-new/coldsweat/coldsweat/models.py", line 326, in connect
    initializer(*initargs)
  File "/Users/samuelrichardson/Library/Mobile Documents/com~apple~CloudDocs/dev-new/coldsweat/coldsweat/models.py", line 326, in connect
    _db.connect()
  File "/Library/Python/2.7/site-packages/peewee.py", line 3296, in connect
    _db.connect()
  File "/Library/Python/2.7/site-packages/peewee.py", line 3296, in connect
    _db.connect()
  File "/Library/Python/2.7/site-packages/peewee.py", line 3296, in connect
    self.initialize_connection(self.__local.conn)
  File "/Library/Python/2.7/site-packages/peewee.py", line 3212, in __exit__
    reraise(new_type, new_type(*exc_args), traceback)
  File "/Library/Python/2.7/site-packages/peewee.py", line 3294, in connect
    **self.connect_kwargs)
  File "/Library/Python/2.7/site-packages/peewee.py", line 3514, in _connect
    self._add_conn_hooks(conn)
  File "/Library/Python/2.7/site-packages/peewee.py", line 3521, in _add_conn_hooks
    self._set_pragmas(conn)
  File "/Library/Python/2.7/site-packages/peewee.py", line 3530, in _set_pragmas
    cursor.execute('PRAGMA %s = %s;' % (pragma, value))
OperationalError: locking protocol
    self.initialize_connection(self.__local.conn)
  File "/Library/Python/2.7/site-packages/peewee.py", line 3212, in __exit__
    reraise(new_type, new_type(*exc_args), traceback)
  File "/Library/Python/2.7/site-packages/peewee.py", line 3294, in connect
    **self.connect_kwargs)
  File "/Library/Python/2.7/site-packages/peewee.py", line 3514, in _connect
    self._add_conn_hooks(conn)
  File "/Library/Python/2.7/site-packages/peewee.py", line 3521, in _add_conn_hooks
    self._set_pragmas(conn)
  File "/Library/Python/2.7/site-packages/peewee.py", line 3530, in _set_pragmas
    cursor.execute('PRAGMA %s = %s;' % (pragma, value))
    self.initialize_connection(self.__local.conn)
  File "/Library/Python/2.7/site-packages/peewee.py", line 3212, in __exit__
OperationalError: locking protocol
    reraise(new_type, new_type(*exc_args), traceback)
  File "/Library/Python/2.7/site-packages/peewee.py", line 3294, in connect
    **self.connect_kwargs)
  File "/Library/Python/2.7/site-packages/peewee.py", line 3514, in _connect
    self._add_conn_hooks(conn)
  File "/Library/Python/2.7/site-packages/peewee.py", line 3521, in _add_conn_hooks
    self._set_pragmas(conn)
  File "/Library/Python/2.7/site-packages/peewee.py", line 3530, in _set_pragmas
    cursor.execute('PRAGMA %s = %s;' % (pragma, value))
    self.initialize_connection(self.__local.conn)
  File "/Library/Python/2.7/site-packages/peewee.py", line 3212, in __exit__
OperationalError: locking protocol
    reraise(new_type, new_type(*exc_args), traceback)
  File "/Library/Python/2.7/site-packages/peewee.py", line 3294, in connect
    **self.connect_kwargs)
  File "/Library/Python/2.7/site-packages/peewee.py", line 3514, in _connect
    self._add_conn_hooks(conn)
  File "/Library/Python/2.7/site-packages/peewee.py", line 3521, in _add_conn_hooks
    self._set_pragmas(conn)
  File "/Library/Python/2.7/site-packages/peewee.py", line 3530, in _set_pragmas
    cursor.execute('PRAGMA %s = %s;' % (pragma, value))
OperationalError: locking protocol
^C^C^C^CProcess PoolWorker-14:
Process PoolWorker-16:
Process PoolWorker-13:
Process PoolWorker-15:
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/pool.py", line 97, in worker
    self.run()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/process.py", line 114, in run
    self.run()
    self.run()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/process.py", line 114, in run
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/pool.py", line 97, in worker
    self._target(*self._args, **self._kwargs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/pool.py", line 97, in worker
    initializer(*initargs)
  File "/Users/samuelrichardson/Library/Mobile Documents/com~apple~CloudDocs/dev-new/coldsweat/coldsweat/models.py", line 326, in connect
    self._target(*self._args, **self._kwargs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/pool.py", line 97, in worker
    _db.connect()
  File "/Library/Python/2.7/site-packages/peewee.py", line 3294, in connect
    initializer(*initargs)
  File "/Users/samuelrichardson/Library/Mobile Documents/com~apple~CloudDocs/dev-new/coldsweat/coldsweat/models.py", line 326, in connect
    initializer(*initargs)
    initializer(*initargs)
  File "/Users/samuelrichardson/Library/Mobile Documents/com~apple~CloudDocs/dev-new/coldsweat/coldsweat/models.py", line 326, in connect
  File "/Users/samuelrichardson/Library/Mobile Documents/com~apple~CloudDocs/dev-new/coldsweat/coldsweat/models.py", line 326, in connect
    _db.connect()
    _db.connect()
  File "/Library/Python/2.7/site-packages/peewee.py", line 3294, in connect
  File "/Library/Python/2.7/site-packages/peewee.py", line 3294, in connect
    _db.connect()
  File "/Library/Python/2.7/site-packages/peewee.py", line 3294, in connect
    **self.connect_kwargs)
  File "/Library/Python/2.7/site-packages/peewee.py", line 3514, in _connect
    self._add_conn_hooks(conn)
KeyboardInterrupt
    **self.connect_kwargs)
  File "/Library/Python/2.7/site-packages/peewee.py", line 3514, in _connect
    self._add_conn_hooks(conn)
KeyboardInterrupt
    **self.connect_kwargs)
  File "/Library/Python/2.7/site-packages/peewee.py", line 3514, in _connect
    self._add_conn_hooks(conn)
    **self.connect_kwargs)
  File "/Library/Python/2.7/site-packages/peewee.py", line 3514, in _connect
    self._add_conn_hooks(conn)
KeyboardInterrupt
KeyboardInterrupt
`

**Comment by richardsonsamuel** [comment]
@passiomatic Do you by any chance know why this happens? Is it me/my system or the code?

I'm on Apple MBP 2016

**Comment by passiomatic** [comment]
Seems related to #88. Are you using sqlite? Multiprocess fetching and sqlite seem to cause this kind of issues on certain Python installations. 

I suggest to set `processes: 0` in your `etc/config` file and try again. Let me know if this work for you.

**Comment by richardsonsamuel** [comment]
Worked! Thanks for your help!
