### ISSUE TITLE
Config - include port configuration for the "serve" command?

### ISSUE THREAD

**Issue by SkyCrawl** [passiomatic/coldsweat#76]
In my case, running `python sweat.py serve` yields:
```
Traceback (most recent call last):
  File "sweat.py", line 12, in <module>
    run()
  File "/share/CACHEDEV1_DATA/MyGit/_app/coldsweat/coldsweat/commands.py", line 207, in run
    handler(parser, options, command_args)        
  File "/share/CACHEDEV1_DATA/MyGit/_app/coldsweat/coldsweat/commands.py", line 61, in command_serve
    httpd = make_server('localhost', options.port, cascade_app)
  File "/opt/lib/python2.7/wsgiref/simple_server.py", line 144, in make_server
    server = server_class((host, port), handler_class)
  File "/opt/lib/python2.7/SocketServer.py", line 408, in __init__
    self.server_bind()
  File "/opt/lib/python2.7/wsgiref/simple_server.py", line 48, in server_bind
    HTTPServer.server_bind(self)
  File "/opt/lib/python2.7/BaseHTTPServer.py", line 108, in server_bind
    SocketServer.TCPServer.server_bind(self)
  File "/opt/lib/python2.7/SocketServer.py", line 419, in server_bind
    self.socket.bind(self.server_address)
  File "/opt/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 98] Address already in use
```
which, as I take it, means the default port `8080` is already used :).

**Comment by SkyCrawl** [comment]
Ah, stupid me. Forgot to check the serve command's help (e.g. `python sweat.py serve --help`). Sincere apologies...

Perhaps it might be beneficial to note this in the setup page, however, for people like me who act faster than think? :)

**Comment by passiomatic** [comment]
> Perhaps it might be beneficial to note this in the setup page, however, for people like me who act faster than think? :)

Nice tip. Done: https://github.com/passiomatic/coldsweat/wiki/Setup#starting-a-local-server
