### ISSUE TITLE
python sweat.py upgrade fail

### ISSUE THREAD

**Issue by vaz-ar** [passiomatic/coldsweat#87]
Hi,
I tried upgrading from 0.9.4 to 0.9.5 and got this error when I tried to run `python sweat.py upgrade` :
```
Traceback (most recent call last):
  File "sweat.py", line 9, in <module>
    from coldsweat.commands import run
  File "/home/coldsweat/coldsweat/__init__.py", line 45, in <module>
    config = load_config(os.path.join(installation_dir, 'etc/config'))
  File "/home/coldsweat/coldsweat/config.py", line 58, in load_config
    for k, v in parser.items(section)
  File "/usr/lib/python2.7/ConfigParser.py", line 655, in items
    for option in options]
  File "/usr/lib/python2.7/ConfigParser.py", line 691, in _interpolate
    self._interpolate_some(option, L, rawval, section, vars, 1)
  File "/usr/lib/python2.7/ConfigParser.py", line 723, in _interpolate_some
    option, section, rest, var)
ConfigParser.InterpolationMissingOptionError: Bad value substitution:
        section: [log]
        option : format
        key    : asctime
        rawval : ] %(process)d %(levelname)s %(message)s
```

**Comment by vaz-ar** [comment]
sorry for this, there was a line in the configuration file that wasn't needed anymore

**Comment by passiomatic** [comment]
Yes, I've forgotten to document that specific change to config file. For the record new [log] section has only two sections: 

```
; Values are: DEBUG (more verbose), INFO, WARNING, ERROR, CRITICAL (less verbose)
;level: INFO

; Comment to avoid logging to a file altogether
filename: coldsweat.log
```
